server:
  port: 6061

spring:
  profiles: dev2
eureka:
  instance:
    hostname: dev2
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://dev1/eureka/