server:
  port: 6060

#用于多个注册中心，当前本机只使用一个注册中心，先注释掉
#spring:
#  profiles: dev1
#eureka:
#  instance:
#    hostname: dev1
#  client:
#    registerWithEureka: false
#    fetchRegistry: false
#    serviceUrl:
#      defaultZone: http://dev2/eureka/

#单机版
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/